version: '3.8'

services:
  app:
    image: 'spring-app:latest'
    build:
      context: .
    container_name: spring-todolist
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: pom.xml
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./logs:/app/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/todolist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ngocquynguyen1
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - SPRING_CACHE_REDIS_TIME_TO_LIVE=300000
      - SPRING_CACHE_REDIS_CACHE_NULL_VALUES=false
      - SPRING_DATA_REDIS_TIMEOUT=60000
      - SRPING.CACHE.CACHE-NAMES=tasks

    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - todolist
  redis:
    image: 'redis:latest'
    container_name: redis_cache
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    networks:
      - todolist
  # db:
  #   image: 'postgres:17.2-alpine3.21'
  #   container_name: pgsql
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=Ngocquynguyen1
  #     - POSTGRES_DB=todolist
  #   networks:
  #     - app_network

volumes:
  postgres-data:
  redis-data:
networks:
  todolist:
    driver: bridge
  app_network:
    driver: bridge